---
title: "pup info"
author: "Katherine Rosencrance"
date: "2023-03-16"
output: html_document
---

When they are born, monk seal pups are black. As they wean and get older, they turn from dark gray with brown on their backs to light gray with yellowish brown bellies. 

Monk seals undergo a yearly "catastrophic molt" where they shed the top layer of their skin and fur, similar to their cousins, elephant seals. Seals that spend a long time at sea foraging in the water can grow algae on their fur that turns it green. Seals that look particularly green may be about to shed to reveal a silvery new coat.

Most Hawaiian monk seals have unique natural markings, such as scars or white spots, on their fur which help researchers at the NPS identify them. Authorized researchers can apply identification tags to their rear flippers. Tagging and tracking, along with identification of unique markings, enable long-term monitoring of individual seals.

Male and female monk seals are farily similar in size. Looking at a seal's belly is the only way to confirm whether it is male or female.

Choose a mom tag number from the options on the left to reveal an interactive data table that displays information about her pups! 


